---
driver_plugin: vagrant
driver_config:
  require_chef_omnibus: true
  customize:
    memory: 1546

provisioner:
  name: chef_zero

platforms:
- name: centos-7.2

suites:
- name: server-community
  run_list:
  - recipe[minitest-handler]
  - recipe[couchbase::server]
  - recipe[couchbase::cluster]
  - recipe[couchbase::buckets]
  attributes:
    couchbase:
      cluster:
        name: "dev"
        username: "admin"
        password: "test1234"
        memory_quota_mb: 512
      buckets:
        one:
          cluster: "dev"
          type: "memcached"
          saslpassword: "nevertellanyone"
          memory_quota_mb: 256
          replicas: 0
        two:
          cluster: "dev"
          type: "couchbase"
          saslpassword: "mustbedifferent"
          memory_quota_percent: 0.5
          replicas: 1
      server:
        password: "whatever"
        package_full_url: http://packages.couchbase.com/releases/4.0.0/couchbase-server-community-4.0.0-centos6.x86_64.rpm
        package_file: couchbase-server-community-4.0.0-centos6.x86_64.rpm
        version: 4.0.0
        memory_quota_mb: 1024
